name: 🔒 Secret Detection Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  secret-scan:
    name: 🔍 Scan for Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history for better scanning
    
    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: 📦 Install Secret Detection Tools
      run: |
        pip install detect-secrets truffleHog bandit safety
    
    - name: 🔍 Run detect-secrets
      run: |
        # Update baseline (only scans new secrets)
        detect-secrets scan --baseline .secrets.baseline --force-use-all-plugins
        
        # Check if there are any new secrets
        if [ $? -ne 0 ]; then
          echo "❌ New secrets detected!"
          echo "::error::Secret detection failed - potential secrets found"
          exit 1
        fi
        
        echo "✅ No new secrets detected"
    
    - name: 🔍 Run TruffleHog on Git History
      run: |
        echo "🔍 Scanning git history for secrets..."
        trufflehog --regex --entropy=False --json . | \
        grep -v "node_modules" | \
        grep -v ".mypy_cache" | \
        head -10 > trufflehog-results.json || true
        
        # Check if any high-confidence secrets found
        if [ -s trufflehog-results.json ]; then
          echo "⚠️ TruffleHog found potential secrets:"
          cat trufflehog-results.json
          echo "::warning::TruffleHog detected potential secrets. Please review."
        else
          echo "✅ TruffleHog: No secrets found"
        fi
    
    - name: 🔒 Security Scan with Bandit
      run: |
        echo "🔍 Running security scan on Python code..."
        cd backend
        bandit -r . -f json -o ../bandit-report.json -x venv/ || true
        bandit -r . -ll -x venv/ || echo "⚠️ Security issues found - please review"
    
    - name: 📊 Upload Scan Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: |
          .secrets.baseline
          trufflehog-results.json
          bandit-report.json
        retention-days: 30
    
    - name: 💬 Comment on PR (if secrets found)
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🔒 Secret Detection Alert
            
            ❌ **Potential secrets detected in this PR!**
            
            Please review the scan results and either:
            1. Remove any real secrets and use environment variables instead
            2. Add false positives to the allowlist in \`.secrets.baseline\`
            
            Check the "Security Scan Results" artifact for details.
            
            **Never commit real API keys, passwords, or secrets to git!**`
          }) 