security:
  ignore-vulnerabilities:
    # python-jose vulnerabilities - migration to PyJWT planned
    70716:
      reason: "Legacy dependency - scheduled for replacement with PyJWT in next sprint"
      expires: "2025-12-31"
    70715:
      reason: "Legacy dependency - scheduled for replacement with PyJWT in next sprint"
      expires: "2025-12-31"

    # ecdsa vulnerabilities - indirect dependency via python-jose
    64459:
      reason: "Indirect dependency via python-jose - will be resolved with PyJWT migration"
      expires: "2025-12-31"
    64396:
      reason: "Indirect dependency via python-jose - will be resolved with PyJWT migration"
      expires: "2025-12-31"

    # Starlette vulnerabilities - keeping compatible versions for FastAPI
    73725:
      reason: "Fixed in newer versions - limited by FastAPI compatibility requirements"
      expires: "2025-12-31"
    68094:
      reason: "Fixed in newer versions - limited by FastAPI compatibility requirements"
      expires: "2025-12-31"

    # python-multipart vulnerabilities - updated to latest compatible version
    66706:
      reason: "Updated to latest version that maintains FastAPI compatibility"
      expires: "2025-12-31"
    74427:
      reason: "Updated to latest version that maintains FastAPI compatibility"
      expires: "2025-12-31"

    # anyio vulnerabilities - using version compatible with OpenAI and FastAPI
    71199:
      reason: "Using latest version compatible with OpenAI SDK and FastAPI"
      expires: "2025-12-31"

    # GitPython vulnerabilities - constrained by trufflehog dependency for secret scanning
    60841:
      reason: "Version constrained by trufflehog secret scanning tool - isolated usage"
      expires: "2025-12-31"
    52322:
      reason: "Version constrained by trufflehog secret scanning tool - isolated usage"
      expires: "2025-12-31"
    60789:
      reason: "Version constrained by trufflehog secret scanning tool - isolated usage"
      expires: "2025-12-31"
    60350:
      reason: "Version constrained by trufflehog secret scanning tool - isolated usage"
      expires: "2025-12-31"
    63687:
      reason: "Version constrained by trufflehog secret scanning tool - isolated usage"
      expires: "2025-12-31"
    52518:
      reason: "Version constrained by trufflehog secret scanning tool - isolated usage"
      expires: "2025-12-31"

  continue-on-vulnerability-error: false
