# Safety policy for Vigor Backend
# Known vulnerabilities that are accepted with mitigation plans

security:
  ignore-vulnerabilities:
    # python-jose vulnerabilities - planned migration to PyJWT
    - 70716: # CVE-2024-33664 - DoS via crafted JWT
        reason: "python-jose dependency - migration to PyJWT planned"
        expires: "2025-12-31"
    - 70715: # CVE-2024-33663 - Algorithm confusion with ECDSA keys
        reason: "python-jose dependency - migration to PyJWT planned"
        expires: "2025-12-31"

    # ecdsa vulnerabilities (dependency of python-jose)
    - 64459: # CVE-2024-23342 - Minerva attack vulnerability
        reason: "ecdsa dependency of python-jose - will be resolved with PyJWT migration"
        expires: "2025-12-31"
    - 64396: # Side-channel attack vulnerability
        reason: "ecdsa dependency of python-jose - will be resolved with PyJWT migration"
        expires: "2025-12-31"
