name: Vigor
options:
  bundleIdPrefix: com.vigor
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

configFiles:
  Debug: Config/Dev.xcconfig
  Release: Config/Prod.xcconfig

targets:
  # ──────────────────────────────────────────────────
  # iPhone App Target
  # ──────────────────────────────────────────────────
  Vigor:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Vigor
        excludes:
          - "**/__pycache__/**"
      - path: Shared
        excludes:
          - "**/__pycache__/**"
    resources:
      - path: Vigor/Assets.xcassets
      - path: Vigor/PrivacyInfo.xcprivacy
      - path: Vigor/Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vigor.app
        INFOPLIST_FILE: Vigor/Info.plist
        CODE_SIGN_ENTITLEMENTS: Vigor/Vigor.entitlements
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) FREE_PROVISIONING
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) DEBUG FREE_PROVISIONING
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited)
    entitlements:
      path: Vigor/Vigor.entitlements

  # ──────────────────────────────────────────────────
  # watchOS App Target (disabled for now — Shared/ has
  # cross-compilation issues to fix first)
  # Re-enable once DetectedWorkout, AnyCodable, etc.
  # are moved to Shared/Models/
  # ──────────────────────────────────────────────────
  # VigorWatch:
  #   type: application
  #   platform: watchOS
  #   deploymentTarget: "10.0"
  #   sources:
  #     - path: VigorWatch
  #       excludes:
  #         - "**/__pycache__/**"
  #     - path: Shared
  #       excludes:
  #         - "**/__pycache__/**"
  #   resources:
  #     - path: VigorWatch/Assets.xcassets
  #   settings:
  #     base:
  #       PRODUCT_BUNDLE_IDENTIFIER: com.vigor.app.watch
  #       INFOPLIST_FILE: VigorWatch/Info.plist
  #       CODE_SIGN_ENTITLEMENTS: VigorWatch/VigorWatch.entitlements
  #       CODE_SIGN_STYLE: Automatic
  #       ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  #       ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  #       SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) FREE_PROVISIONING
  #       SDKROOT: watchos
  #       SKIP_INSTALL: YES
  #     configs:
  #       Debug:
  #         SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) DEBUG FREE_PROVISIONING
  #       Release:
  #         SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited)
  #   entitlements:
  #     path: VigorWatch/VigorWatch.entitlements

  # ──────────────────────────────────────────────────
  # Unit Tests
  # ──────────────────────────────────────────────────
  VigorTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: VigorTests
        excludes:
          - "**/__pycache__/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vigor.app.tests
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) DEBUG FREE_PROVISIONING
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Vigor
