"""Add Microsoft Entra ID support for VedUser standard

Revision ID: 43d7cdb5fc30
Revises: d538cf82b14a
Create Date: 2025-06-28 17:18:21.422500

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '43d7cdb5fc30'
down_revision = 'd538cf82b14a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('entra_id', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('given_name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('family_name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('permissions', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('ved_profile', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_user_profiles_entra_id'), 'user_profiles', ['entra_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_entra_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'ved_profile')
    op.drop_column('user_profiles', 'permissions')
    op.drop_column('user_profiles', 'subscription_tier')
    op.drop_column('user_profiles', 'family_name')
    op.drop_column('user_profiles', 'given_name')
    op.drop_column('user_profiles', 'name')
    op.drop_column('user_profiles', 'entra_id')
    # ### end Alembic commands ###
