"""Add password field to user

Revision ID: cd62a1da2fe2
Revises: 15a24591b6f5
Create Date: 2025-06-01 00:21:05.812521

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd62a1da2fe2"
down_revision = "15a24591b6f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles", sa.Column("hashed_password", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "hashed_password")
    # ### end Alembic commands ###
