# Vigor Platform - Development Environment Configuration
# Azure-specific configuration for development deployment

environment:
  name: "dev"
  region: "East US"

resources:
  # Resource naming convention: vigor-{environment}-{resource-type}
  resource_group: "vigor-dev-rg"
  app_service_plan: "vigor-dev-asp"
  app_service: "vigor-dev-app"
  container_registry: "vigordevacr"
  storage_account: "vigordevstorage"
  key_vault: "vigor-dev-kv"
  postgresql: "vigor-dev-postgres"
  application_insights: "vigor-dev-insights"
  cdn_profile: "vigor-dev-cdn"

database:
  tier: "Basic"
  capacity: 1
  storage_mb: 5120
  backup_retention_days: 7
  geo_redundant_backup: false
  auto_grow: true
  ssl_enforcement: true

app_service:
  sku: "B1" # Basic tier for development
  capacity: 1
  auto_scale_enabled: false
  always_on: false # Cost optimization for dev

storage:
  tier: "Standard"
  replication: "LRS" # Locally redundant for dev

monitoring:
  log_retention_days: 30
  metrics_retention_days: 30
  alert_rules_enabled: false # Minimal alerting for dev

security:
  managed_identity_enabled: true
  key_vault_access_enabled: true
  https_only: true
  ftps_state: "Disabled"

scaling:
  min_instances: 1
  max_instances: 2
  scale_up_threshold: 80
  scale_down_threshold: 20

costs:
  daily_budget_usd: 10
  monthly_budget_usd: 300
  auto_shutdown_enabled: true
  auto_shutdown_time: "22:00" # 10 PM EST

features:
  custom_domain_enabled: false
  ssl_certificate_enabled: false
  cdn_enabled: false
  backup_enabled: false
  high_availability: false
