name: Build and Deploy Static Web App

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
        default: "prod"

jobs:
  deploy-frontend:
    name: Build and Deploy Static Web App
    runs-on: ubuntu-latest
    needs: [build-frontend, validate-infra]
    if: ${{ env.USE_DIRECT_DEPLOYMENT == 'true' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: |
          echo "📦 Installing frontend dependencies..."
          cd frontend
          npm ci

      - name: Build
        run: |
          echo "🔨 Building frontend..."
          cd frontend
          npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STATIC_WEB_APP_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend/dist"
          api_location: ""
          output_location: ""
