---
name: Automated PR Processing

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed
  status:

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'auto-merge') &&
      github.event.pull_request.draft == false
    steps:
      - name: Auto-merge qualifying PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "auto-merge,!do-not-merge"
          MERGE_REMOVE_LABELS: "auto-merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: "auto-merge"
          UPDATE_METHOD: "rebase"

  pr-verification:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify PR size
        id: verify-pr-size
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          PR_FILES=$(gh pr view $PR_NUM --json files -q '.files[].path')
          PR_ADDITIONS=$(gh pr view $PR_NUM --json additions -q '.additions')
          PR_DELETIONS=$(gh pr view $PR_NUM --json deletions -q '.deletions')
          PR_CHANGES=$((PR_ADDITIONS + PR_DELETIONS))

          echo "PR has $PR_CHANGES changes ($PR_ADDITIONS+ $PR_DELETIONS-)"

          if [[ $PR_CHANGES -gt 300 ]]; then
            echo "::warning::This PR exceeds the recommended 300 lines limit."
            echo "::warning::Please consider breaking it into smaller PRs."
            echo "size_warning=true" >> $GITHUB_OUTPUT
          else
            echo "size_warning=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR age
        id: check-pr-age
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          PR_CREATED_AT=$(gh pr view $PR_NUM --json createdAt -q '.createdAt')
          PR_CREATED_TIMESTAMP=$(date -d "$PR_CREATED_AT" +%s)
          CURRENT_TIMESTAMP=$(date +%s)

          # Calculate PR age in days
          PR_AGE_SECONDS=$((CURRENT_TIMESTAMP - PR_CREATED_TIMESTAMP))
          PR_AGE_DAYS=$((PR_AGE_SECONDS / 86400))

          echo "PR age: $PR_AGE_DAYS days"

          if [[ $PR_AGE_DAYS -gt 2 ]]; then
            echo "::warning::This PR is older than 2 days."
            echo "::warning::Please consider resolving outstanding issues."
            echo "age_warning=true" >> $GITHUB_OUTPUT
          else
            echo "age_warning=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify PR has description
        id: verify-description
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          PR_BODY=$(gh pr view $PR_NUM --json body -q '.body')

          if [[ -z "$PR_BODY" || ${#PR_BODY} -lt 20 ]]; then
            echo "::warning::This PR has an insufficient description."
            echo "::warning::Please add more details about the changes."
            echo "description_warning=true" >> $GITHUB_OUTPUT
          else
            echo "description_warning=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remind about tests
        id: check-tests
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          PR_FILES=$(gh pr view $PR_NUM --json files -q '.files[].path')

          # Check if PR contains test files
          TEST_PATTERN='(test|spec|__tests__|_test)\.(js|jsx|ts|tsx|py|go|rb|java|php)'
          if ! echo "$PR_FILES" | grep -qE "$TEST_PATTERN"; then
            # If no test files found, check if PR touches code that needs tests
            CODE_PATTERN='\.(js|jsx|ts|tsx|py|go|rb|java|php)$'
            if echo "$PR_FILES" | grep -qE "$CODE_PATTERN"; then
              echo "::warning::This PR modifies code without test updates."
              echo "::warning::Please consider adding tests."
              echo "tests_warning=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "tests_warning=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR issues
        if: |
          steps.verify-pr-size.outputs.size_warning == 'true' ||
          steps.check-pr-age.outputs.age_warning == 'true' ||
          steps.verify-description.outputs.description_warning == 'true' ||
          steps.check-tests.outputs.tests_warning == 'true'
        run: |
          COMMENT="## PR Check Results\n\n"

          SIZE_OUT="${{ steps.verify-pr-size.outputs.size_warning }}"
          if [[ "$SIZE_OUT" == "true" ]]; then
            COMMENT+="⚠️ **Size Warning**: This PR exceeds 300 lines limit.\n"
            COMMENT+="Please consider breaking it into smaller PRs.\n\n"
          fi

          AGE_OUT="${{ steps.check-pr-age.outputs.age_warning }}"
          if [[ "$AGE_OUT" == "true" ]]; then
            COMMENT+="⏱️ **Age Warning**: This PR is older than 2 days.\n"
            COMMENT+="Please consider resolving outstanding issues.\n\n"
          fi

          DESC_OUT="${{ steps.verify-description.outputs.description_warning }}"
          if [[ "$DESC_OUT" == "true" ]]; then
            COMMENT+="📝 **Description Warning**: Insufficient description.\n"
            COMMENT+="Please add more details about the changes.\n\n"
          fi

          TEST_OUT="${{ steps.check-tests.outputs.tests_warning }}"
          if [[ "$TEST_OUT" == "true" ]]; then
            COMMENT+="🧪 **Testing Warning**: Code changes without tests.\n"
            COMMENT+="Please consider adding tests.\n\n"
          fi

          COMMENT+="\nFor more information, see our "
          COMMENT+="[Development Guide](../blob/main/docs/dev_pr_mgmt.md)."

          PR_NUM="${{ github.event.pull_request.number }}"
          gh pr comment $PR_NUM --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
